version: '3.8'

services:
  api-test:
    build:
      context: .
      target: tester
    volumes:
      - .:/app
    env_file:
      - .env.test
    command: npm run test

  api:
    build:
      context: .
      target: runner
    ports:
      - "8000:8000"
    volumes:
      - db_data:/data
    env_file:
      - .env
    depends_on:
      api-test:
        condition: service_completed_successfully

volumes:
  db_data:
