version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - db_data:/data
    env_file:
      - .env

  api-test:
    build: .
    command: npm run test
    volumes:
      - .:/app
    env_file:
      - .env.test
    depends_on:
      - api

volumes:
  db_data:
